# Generated by Django 5.1.1 on 2024-10-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_discount_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='products',
            new_name='product',
        ),
    ]
