# Generated by Django 5.1.1 on 2024-10-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_discount_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
